### ISSUE TITLE
Bot - Administratif - Premiere Version

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-backend#43]
Notes prises en atelier : 

### mecanisme d’interactions avec le bot
- créer un salon avec le bot (à définir)
- salon chiffré

### où le déployer?
- un bot par instance pour avoir acces aux API admin
- un serveur à part? sur le serveur synapse

### garantir la sécurité de l'acces au bot
- verification mutuelle des appareils
- clef de sécurité
- whitelister “nom d’utilisateurs” ou “id de salon”
    - whitelister les devices de
- bot seulement pour l’équipe tchap
- Comment se prevenir d’un sabotage d’un membre de l’équipe :
    - supprimer les droits quand un tchap@s part
    - faire valider les opérations par une autre personne de l’équipe comme une “review”

### audit
- audit des actions d’admin
- logguer sur le serveur les actions
- commande !help pour avoir la liste des commandes

```[tasklist]
### Tasks
- [x] Reset password pour un user => [v0.0.7](https://github.com/tchapgouv/matrix-admin-bot/releases/tag/v0.0.7)
- [x] https://github.com/tchapgouv/tchap-infra/issues/2853
```

**Comment by odelcroi** [comment]
repo : https://github.com/tchapgouv/matrix-admin-bot

**Comment by julie-ri** [comment]
merci @mcalinghee c'est bcp plus clair avec ta description

**Comment by mcalinghee** [comment]
Ticket clos

Les prochaines taches sur le bot :

- [ ] https://github.com/tchapgouv/tchap-backend/issues/47
- [ ] https://github.com/tchapgouv/tchap-backend/issues/48
- [ ] https://github.com/tchapgouv/tchap-backend/issues/49
- [ ] https://github.com/tchapgouv/tchap-backend/issues/50
